version: "3.4"

services:
  postgresql_database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database-data-shop:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=andrade
      - POSTGRES_PASSWORD=123654

volumes:
  database-data-shop: