version: "3.8"

services:
  postgresql_database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database-data-shop:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=andrade
      - POSTGRES_PASSWORD=123654

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net

volumes:
  database-data-shop:
  redis-data:


networks:
  redis-net: